# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telephone'),
        ),
    ]
